#!/bin/zsh

export PASSWORD_STORE_DIR=${PASSWORD_STORE_DIR:-$HOME/.password-store}
# export PINENTRY_USER_DATA=curses
export EDITOR='vim --clean'

SELECT=${$(find $PASSWORD_STORE_DIR -name "*.gpg" | sed 's@^'"$PASSWORD_STORE_DIR"'\/@@'|sort |peco --prompt="Entry> "):r}

if [ -z $SELECT ];
  then return;
fi

ACT=$(echo "edit
show
show-c
rm
cp
mv
otp" | peco --prompt="Act> ")

if [ -z $ACT ];
then return;
fi


# show once to pass pinentry. For this, don't disable pinentry caching.
## I give up pinentry-curses. I choose pinentry-gtk2, then I don't need.
# pass show $SELECT 
# clear

# case $TERM in 
#   screen*)
#     tmux clear-history
#     clear
#     ;;
#   *)
#     clear
#     ;;
# esac

case $ACT in
  show-c)
    # For ``pass show -c``, use this
    # LINEID=$(pass show $SELECT | cat -n | peco | cut -f1)
    # pass show -c${LINEID// /} $SELECT

    # For Tmux buffer, use this
    select_lines=$(pass show $SELECT | cat | peco )
    tmux set-buffer $select_lines
    ;;
  cp|mv)
    # If you want peco as ``read``, use it. 
    #NEWPATH=$(echo | peco --prompt "New Path > " --print-query --query $SELECT)
    NEWPATH=$SELECT
    #vared -c -p 'New path >' NEWPATH
    vared -p 'New path >' NEWPATH
    if [ -z $NEWPATH ];
      then return;
    fi
    pass $ACT $SELECT $NEWPATH
    ;;
  *)
    pass $ACT $SELECT
    ;;
esac


